name: Test Validation

on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - feature

jobs:
  validate_other:
    name: test validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Build C-ext
        working-directory: ./10
        run: python setup.py install

      - name: Check flake8
        run: flake8 .

      - name: Check pylint
        if: ${{ always() }}
        run: pylint ./*/*.py

      - name: Check tests with pytest
        if: ${{ always() }}
        run: coverage run -m pytest .

      - name: Check test coverage
        run: coverage report -m
